### PR TITLE
Auto release circleci

### PR DESCRIPTION
**Pull request by svroonland**
This PR performs an automatic release to Sonatype for every PR merged to master.

* Dynamic versioning based on nr of commits since last git tag instead of AWS version. Every commit to master will generate a patch-level version increment.
* Push a git tag. 
* Share workspace between build stages to store build artifacts
* Publish to Sonatype after successful build
* Also: bump docker images used for building to have the latest SBT and scala version

Setup instructions:
* Make an initial version tag. Should probably be higher than the latest version to avoid confusion, so `v3.0` something?
* Configuring an SSH key with write access, see https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys. Do not set the `GITHUB_TOKEN` env var. The fingerprint in config.yml is one that is valid in my fork only. 
* Define the fingerprint in the `SSH_FINGERPRINT` env var
* Remove the other deploy key that was created automatically by CircleCI. 
* Add env vars `SONATYPE_USERNAME`, `SONATYPE_PASSWORD`
* Add env vars `PGP_PASSPHRASE` and `PGP_SECRET` (base64 encoded private key)

### CODE REVIEW

**Comment by vigoo** [comment]
Thank you for doing this! I will do the setup steps tomorrow. 

One extra thing I would do is to mix the auto-incremented version introduced here with my original idea of having (part of) the underlying AWS library version part of the zio-aws library version. I checked how it works and based on that the following would be a good solution:

- create an extra command that is very similar to `ciReleaseTagNextVersion` but instead of incrementing the last segment, it would get the AWS library version from a property (set in `Common`) and check if the current version's middle two segments coming from the last git tag matches that. If not it creates a new git tag with keeping the first segment, setting the next two, and setting the last to 0
- `Utils` from `sbt-ci-release-early` and `jgit` should be on the classpath already so they can be used to implement this
- this new command is to be called before `ciReleaseTagNextVersion` from CircleCI
- after that everything can run as it is in this PR, `sbt-ci-release-early` increments the last digit and does the release

This way the major version segment can be used to mark major changes, we don't loose the connection with the AWS library version, and its still safe to do commits in between AWS releases. Only weird thing that there will never be a release ending with `.0` but I think that's not a big deal.

How do you like the idea?
Would you like to implement this in this PR? If not I'm happy to do this part separately.

**Comment by svroonland** [comment]
I'm not sure I completely understand what the version would be in specific cases, but sounds like it could work.

To be honest I've had my share of SBT woes for now, so I'll leave that part to you :) Happy to help if there's anything specific you want to know of course.

**Comment by vigoo** [comment]
Sure thanks for your work! I hope I will have time soon to set everything up and merge this!

**Comment by svroonland** [comment]
What we could do to get this merged now already is to disable the automatic tagging part, so you have manual control over the version number for now. Then when you create a tag, it will run the sonatype release. Good idea?

**Comment by vigoo** [comment]
No need for that, I will:
- set up the keys etc
- tag to 3.awsversion.0
- merge this
- before merging another aws update PR, I add the task I described above

**Pull request merged**
